### ISSUE TITLE
Cannot debug 410 Server Gone errors

### ISSUE THREAD

**Issue by ozanhazer** [ankitpokhrel/tus-php#232] opened 2020-01-16 17:58 UTC
When I upload multiple files using uppy, sometimes it fails to upload some of the files with http error code 410. If I retry the failed files they upload successfully.

I'm still investigating the issue, might be caused by uppy but the problem with tus-php is, it's impossible to understand what's going on without looking at the source code since the actual reason of the error is not logged or returned back to the client.

**Comment by ankitpokhrel** [comment] 2020-01-25 10:49
Hi @ozanhazer, 

Apologies for the late response. `410 (HTTP_GONE)` status is returned when the server cannot find a file for a valid request. This happens if the file status is not properly saved in the cache or if the file doesn't exist during the delete request. The issue is most likely with the cache. You can check the cache to see if there is an entry for that upload id which you are trying to resume/patch. If there is none or entry is empty for the id, the server will send 410.

I agree that there is no proper way to debug this at the moment. I would consider adding a debug/verbose mode to make it easier to debug but it might not happen anytime soon. However, we are happy to help if anyone wants to work on it.

**Comment by Amerlander** [comment] 2020-03-20 20:25
I also try to deal with 410 (gone) errors. I hava an setup which worked fine on localhost using xampp. Then I moved it on a server into a docker container. At first everything worked fine, but after a few days now I can't upload any file at all and even retrying doesn't help. I use Uppy and it only shows that I have an 410 error.

I use just file based caching. What would be steps to check the cache for entries?

**Comment by Amerlander** [comment] 2020-03-21 20:41
Never mind, I found the cache file in `/vendor/ankitpokhrel/tus-php/.cache` and it was not readable since I copied the `/vendor` folder

**Comment by samundra** [comment] 2020-03-23 04:22
@Amerlander Glad you found the solution. Can we close this issue if you feel you have found your solution?

**Comment by Amerlander** [comment] 2020-03-23 09:29
Yes, for me it can be closed

**Closed** 2020-03-26 11:41 UTC
Labels: help/support
