### ISSUE TITLE
Cors Problem

### ISSUE THREAD

**Issue by alhaji-aki** [ankitpokhrel/tus-php#133] opened 2019-03-26 15:19 UTC
Hello there, I keep getting cors errors. I created a new middleware to handle cors and when I remove the Access-Control-Allow-Origin I get this error "No 'Access-Control-Allow-Origin' header is present on the requested resource." but when I add it I get an error "The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:3000, http://localhost:3000', but only one is allowed." I am using this package along side Spatie Cors. Any help? I am using this in Laravel 5.7

**Comment by pdiveris** [comment] 2019-03-26 15:23
Can you show us what's in your middleware?

**Comment by alhaji-aki** [comment] 2019-03-26 15:27
`<?php

namespace App\Http\Middleware;

use TusPhp\Request;
use TusPhp\Response;

class TusCorsMiddleware
{
    /** @const int 24 hours access control max age header */
    const HEADER_ACCESS_CONTROL_MAX_AGE = 86400;

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Response $response)
    {
        $response->setHeaders([
            'Access-Control-Allow-Methods' => implode(',', $request->allowedHttpVerbs()),
            'Access-Control-Allow-Headers' => 'Origin, X-Requested-With, Content-Type, Content-Length, Upload-Key, Upload-Checksum, Upload-Length, Upload-Offset, Tus-Version, Tus-Resumable, Upload-Metadata',
            'Access-Control-Expose-Headers' => 'Upload-Key, Upload-Checksum, Upload-Length, Upload-Offset, Upload-Metadata, Tus-Version, Tus-Resumable, Tus-Extension, Location',
            'Access-Control-Max-Age' => self::HEADER_ACCESS_CONTROL_MAX_AGE,
        ]);
    }
}`

**Comment by pdiveris** [comment] 2019-03-26 15:33
You said this is using the Spatie Cors package? Have you published the vendor config? If yes, what's in your `config/cors.php`?

**Comment by alhaji-aki** [comment] 2019-03-26 15:37
Yes I have published the config file

`
<?php

return [

    /*
     * A cors profile determines which origins, methods, headers are allowed for
     * a given requests. The `DefaultProfile` reads its configuration from this
     * config file.
     *
     * You can easily create your own cors profile.
     * More info: https://github.com/spatie/laravel-cors/#creating-your-own-cors-profile
     */
    'cors_profile' => Spatie\Cors\CorsProfile\DefaultProfile::class,

    /*
     * This configuration is used by `DefaultProfile`.
     */
    'default_profile' => [

        'allow_credentials' => false,

        'allow_origins' => [
            '*',
        ],

        'allow_methods' => [
            'POST',
            'GET',
            'OPTIONS',
            'PUT',
            'PATCH',
            'DELETE',
            'HEAD'
        ],

        'allow_headers' => [
            // 'Content-Type',
            // 'X-Auth-Token',
            // 'Origin',
            // 'Authorization',
            '*',
        ],

        'expose_headers' => [
            'Cache-Control',
            'Content-Language',
            'Content-Type',
            'Expires',
            'Last-Modified',
            'Pragma',
        ],

        'forbidden_response' => [
            'message' => 'Forbidden (cors).',
            'status' => 403,
        ],

        /*
         * Preflight request will respond with value for the max age header.
         */
        'max_age' => 60 * 60 * 24,
    ],
];
`

This is the content of the config file

**Comment by pdiveris** [comment] 2019-03-26 15:40
Can try to change `'allow_origins' => [ '*', ] ` to `'allow_origins' => [ 'localhost' ]` and see what happens -  as a test, not as **the** solution!

**Comment by alhaji-aki** [comment] 2019-03-26 15:48
@pdiveris It is still the same

**Comment by pdiveris** [comment] 2019-03-26 15:48
OK, that's weird. Let me do a check over here.

**Comment by alhaji-aki** [comment] 2019-03-26 15:53
Ok

**Comment by pdiveris** [comment] 2019-03-26 15:56
If you change your `'allow_origins' => [ 'localhost' ]` to `'allow_origins' => [ 'bob' ]` does the error message reflect that? I.e. mention 'bob' twice?

**Comment by alhaji-aki** [comment] 2019-03-26 16:03
Thank you @pdiveris The cors problem is no longer no more...

**Comment by alhaji-aki** [comment] 2019-03-26 16:16
But now I am seeing this error... net::ERR_NAME_NOT_RESOLVED.

**Comment by pdiveris** [comment] 2019-03-26 16:28
Are you using valet? Change localhost to a normative name and put it in /etc/hosts.

**Comment by alhaji-aki** [comment] 2019-03-26 16:29
It has changed to No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by alhaji-aki** [comment] 2019-03-26 16:30
I have 

> Are you using valet? Change localhost to a normative name and put it in /etc/hosts.

I have done this. Now it has changed to No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by alhaji-aki** [comment] 2019-03-30 16:10
Still not found a solution to this. I have even removed spatie cors, and every cors middleware but still not working... So frustrating at the moment...

**Comment by alhaji-aki** [comment] 2019-03-30 16:12
This is my route
`Route::any('/submit/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*');`

Then I created a TusServiceProvider and in the register method This is what I did
`$this->app->singleton('tus-server', function ($app) {
            $server = new TusServer();

            $server
                ->setApiPath('/api/submit') // tus server endpoint.
                ->setUploadDir(storage_path('app/public/uploads')); // uploads dir.

            $postUploadProcessing = new SubmissionController;

            $server->event()->addListener('tus-server.upload.complete', [$postUploadProcessing, 'store']);

            return $server;`

**Comment by ankitpokhrel** [comment] 2019-04-03 03:43
Hi @alhaji-aki 

If you are using [TusPHP Cors Middleware](https://github.com/ankitpokhrel/tus-php/blob/master/src/Middleware/Cors.php#L19), try changing `'Access-Control-Allow-Origin' => $request->header('Origin')` to `'Access-Control-Allow-Origin' => '*'` in your local.

If this still doesn't work for you then please list all the steps you followed and changes you made. Also the snapshot of actual error would be helpful.

**Comment by xzessmedia** [comment] 2019-04-03 14:25
im using TusPHP together with Symfony which works great, but i was not able to get around the cors issue.. when i use my react frontend from a local dev server it works without problems and i can upload a file but im using a cors browser plugin for my local development.
on my remote im using nelmios cors with symfony and no cors browser plugin. it works for all routes except the tus route.
i also tried to skip the default cors middleware shipped with TusPHP without an effect.

did i miss something here?

**Comment by ankitpokhrel** [comment] 2019-04-04 03:24
> on my remote im using nelmios cors with symfony and no cors browser plugin. it works for all routes except the tus route.

Hi @xzessmedia , can you skip tus cors middleware and see if it works for you

```php
$server->middleware()->skip(\TusPhp\Middleware\Cors::class);
```

**Comment by alhaji-aki** [comment] 2019-04-04 08:54
Hello

> Hi @alhaji-aki
> 
> If you are using [TusPHP Cors Middleware](https://github.com/ankitpokhrel/tus-php/blob/master/src/Middleware/Cors.php#L19), try changing `'Access-Control-Allow-Origin' => $request->header('Origin')` to `'Access-Control-Allow-Origin' => '*'` in your local.
> 
> If this still doesn't work for you then please list all the steps you followed and changes you made. Also the snapshot of actual error would be helpful.

Hello @ankitpokhrel 
I switched to [barryvdh/laravel-cors](https://github.com/barryvdh/laravel-cors).
In my service TusServiceProvider I skipped the TusPHP Cors Middleware and now I am not getting the multiple values error again but I am getting a new set of errors which looks like this
![Capture](https://user-images.githubusercontent.com/19788708/55542542-ca533c80-56b6-11e9-864d-2240fd894d46.PNG)

Now my TusServiceProvider looks like this
`<?php

namespace App\Providers;

use TusPhp\Tus\Server as TusServer;
use Illuminate\Support\ServiceProvider;
use App\Http\Controllers\Submission\SubmissionController;
use TusPhp\Middleware\Cors;

class TusServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('tus-server', function ($app) {
            $server = new TusServer();

            $server
                ->setApiPath('/api/submit') // tus server endpoint.
                ->setUploadDir(storage_path('app/public/uploads')); // uploads dir.

            $server->middleware()->skip(Cors::class);

            $postUploadProcessing = new SubmissionController;

            $server->event()->addListener('tus-server.upload.complete', [$postUploadProcessing, 'store']);

            return $server;
        });
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }
}
`
and this is my route
`Route::any('/submit/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*');`

My cors config file looks like this

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Laravel CORS
    |--------------------------------------------------------------------------
    |
    | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
    | to accept any value.
    |
    */

    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedOriginsPatterns' => [],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => ['*'],
    'maxAge' => 0,

];`
and oh I have added \Barryvdh\Cors\HandleCors::class, to my middleware.

**Comment by ankitpokhrel** [comment] 2019-04-04 09:17
@alhaji-aki I assume you are passing your route through the laravel cors middleware?

```php
Route::any('/submit/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*')->middleware('your \Barryvdh\Cors\HandleCors middleware');
```

**Comment by alhaji-aki** [comment] 2019-04-04 09:37
@ankitpokhrel yeah it is placed on all middlewares. So I placed it the Kernel. It looks like this
![Capture](https://user-images.githubusercontent.com/19788708/55545666-333db300-56bd-11e9-86d3-7348f003a953.PNG)

**Comment by xzessmedia** [comment] 2019-04-04 11:53
> 
> 
> > on my remote im using nelmios cors with symfony and no cors browser plugin. it works for all routes except the tus route.
> 
> Hi @xzessmedia , can you skip tus cors middleware and see if it works for you
> 
> ```
> $server->middleware()->skip(\TusPhp\Middleware\Cors::class);
> ```

hi thanks for the quick reply, always good  to see repositories aliveness 👍 
unfortunately i already tried that as i stated before.
it does not do any effect for me in terms of cors.

**Comment by pdiveris** [comment] 2019-04-04 11:55
Hey,

Is your source code open source? I mean, is there a way for me to get it and run it locally? (sorry for delay, I've been away for a week on b'day holiday.)

**Comment by xzessmedia** [comment] 2019-04-04 12:08
im very sorry i know it would be helpful but unfortunately im not allowed in contract

**Comment by pdiveris** [comment] 2019-04-04 12:13
Yes sure. How about the two relevant bits - I think you've already copied and pasted some of that code. Could you do that again in a single post so I know what I am looking at emulating?

**Comment by pdiveris** [comment] 2019-04-04 12:16
Actually don't bother - I've got enough above. Let me have a look.

**Comment by xzessmedia** [comment] 2019-04-04 12:40
since my other routes work without problems, maybe the middleware skip does not work?

this is my getServer()
`public function getServer()
    {
        $server = new Server();
        $server->setApiPath('/tus'); // tus server endpoint.
        $server->setUploadDir($this->params->get('kernel.project_dir') . '/public/uploads'); // uploads dir.

        $server->middleware()->skip(Cors::class);
        
        return $server;
    }`

**Comment by pdiveris** [comment] 2019-04-04 12:44
So, let me understand something. Why are we seeing rowa.test and localhost? What TUS client are using?

**Comment by xzessmedia** [comment] 2019-04-04 12:46
> 
> 
> So, let me understand something. Why are we seeing `rowa.test` and `localhost`? What TUS client are using?

who do you mean?
im using it with uppy in frontend V. ^0.30.3

**Comment by pdiveris** [comment] 2019-04-04 12:56
Yes, I had a similar problem with uppy which insisted in resolving my host with one name and mnot respecting another one. I edited uppy.js line 11425 (of the non uglified version) and did this:

```javascript
                    var e = this;
                    this.url = this.url.replace('zoro', 'tus');
```
I also edited line 11447 of the same un-uglified version and did the same

```javascript
                    var e = this;
                    this.url = this.url.replace('zoro', 'tus');
```
Note that uppy insisted picking **zoro** as the hostname for a host configured also as **tus**. I can't remembered if I found the unuglified version or expanded it my self. If you can't find one let me know and will attach to post so you can try. This might be irrelevant but I now remember that I spent two days on this and it was driving me mad. I ought to report it to the uppy guys really. Give it a go!

**Comment by pdiveris** [comment] 2019-04-04 13:03
Here's my edited version of uppy.js. As I said, nothing to lose. Just change the hostnames to reflect your env and fingers crossed!

[uppy.js.zip](https://github.com/ankitpokhrel/tus-php/files/3043519/uppy.js.zip)

**Comment by alhaji-aki** [comment] 2019-04-04 15:04
> So, let me understand something. Why are we seeing `rowa.test` and `localhost`? What TUS client are using?

rowa.test is the url for the api. I am using valet to serve the api application in laravel locally and the client app is built with vue and nuxt js which is a different project and is running on localhost:3000

**Comment by pdiveris** [comment] 2019-04-04 15:24
Can't you have both in the same domain? E.g. app.local and rowa.local or something?

**Comment by alhaji-aki** [comment] 2019-04-04 15:41
Erm... not that I can think of currently

**Comment by ankitpokhrel** [comment] 2019-04-04 16:10
> ![Capture](https://user-images.githubusercontent.com/19788708/55542542-ca533c80-56b6-11e9-864d-2240fd894d46.PNG)

@alhaji-aki @xzessmedia this is not an issue in server side. You server is already accepting request from  all url (`*`). When you send a request from frontend, your request header must contain `Access-Control-Allow-Origin: http://app.test` header which is what the error is referring to.

So, make sure your client is sending that header when sending the request. Once that is included in your request, it doesn't matter whether you use TusPHP cors middleware or any other third party middleware in server side.

**Comment by pdiveris** [comment] 2019-04-04 16:13
See above, the issue is with your client, not the server. Are the two instances two different IP addresses?

**Comment by alhaji-aki** [comment] 2019-04-04 16:38
I am using uppy js for my client side

**Comment by pdiveris** [comment] 2019-04-04 16:43
Yes, I've gathered that. What I am suggesting is that uppy is not playing nice, not the PHP script. If I were you I'd try to do the past and put/post requests from postman with the appropriate headers, to see what i am getting back. By appropriate headers I mean:

```sql
Access-Control-Allow-Origin: http://app.test
```

**Comment by alhaji-aki** [comment] 2019-04-04 17:11
Thank you @pdiveris I tried using postman to check my request. 
So when I tried the PATCH Request I got this error back. Unable to open C:\xampp\htdocs\rowavision\storage\app/public/uploads\support2.PNG

**Comment by pdiveris** [comment] 2019-04-04 17:15
Yes sure, that's probably due to the slashes/backslashes. However, it does indicate that it is uppy that's not sending the right headers. As you can see from the error you posted above Postman doesn't suffer the Allow-Origin problem. I suspect you have to post this problem to the uppy guys. As I said, I am using uppy.js with Laravel and tus-php and I had to edit uppy.js to force it to send the correct hostname!

**Comment by alhaji-aki** [comment] 2019-04-04 17:19
> Yes sure, that's probably due to the slashes/backslashes. However, it does indicate that it is uppy that's not sending the right headers. As you can see from the error you posted above Postman doesn't suffer the Allow-Origin problem. I suspect you have to post this problem to the uppy guys. As I said, I am using uppy.js with Laravel and tus-php and I had to edit uppy.js to force it to send the correct hostname!

@pdiveris ok I will do that and also can u be kind enough to paste your implementation of your TusServiceProvider?

**Comment by pdiveris** [comment] 2019-04-04 17:28
Yes sure, here it is:

This is my service provider:
```php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use TusPhp\Tus\Server as TusServer;

class TusServiceProvider extends ServiceProvider
{
  // ...
  
  /**
   * Register the application services.
   *
   * @return void
   */
  public function register()
  {
    $this->app->singleton('tus-server', function ($app) {
      $server = new TusServer('redis');
      
      $server
        ->setApiPath('/tus') // tus server endpoint.
        ->setUploadDir(storage_path('app/public/uploads')); // uploads dir.
      
      return $server;
    });
  }
  
  // ...
}
```

This is my routes.php:

```php
 Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();
    
    return $response->send();
  })->where('any', '.*');
```

and this is my app.php

```
        App\Providers\TusServiceProvider::class,
```

I don't seem to be setting any headers anywhere though. I am runningboth within the same "domain" (.dev).

**Comment by MichalKrakow** [comment] 2019-04-11 09:24
Hey i've just run into the same issue. How do You recon the issue is on uppy's side.
For what i can see the options request goes with headers:
```
Access-Control-Request-Headers: tus-resumable,upload-length,upload-metadata
Access-Control-Request-Method: POST
Origin: http://localhost:3000
Referer: http://localhost:3000/tus-test
```
followed by post request with headers: 
```
Origin: http://localhost:3000
Referer: http://localhost:3000/tus-test
Tus-Resumable: 1.0.0
Upload-Length: 244973
Upload-Metadata: name X0lNR184NzA1LmpwZw==,type aW1hZ2UvanBlZw==,filetype aW1hZ2UvanBlZw==,filename X0lNR184NzA1LmpwZw==
```
so what's wrong about this ?

the server responds on post request with shitty header containing: 
```
Access-Control-Allow-Origin: http://localhost:3000, http://localhost:3000
```
can you lead me into the cause and some solution ?

**Comment by pdiveris** [comment] 2019-04-11 09:31
I can't I am afraid as I am not the author of that code. It would take me exactly the same time to find where that gets set as it would take you. Sorry.

**Comment by MichalKrakow** [comment] 2019-04-11 10:50
@ankitpokhrel 
correct me if i'm wrong,
422 response means that server cannot process the request (fails at some point and breaks execution) and therefore it does not send the headers wchich are added later on with middleware. So i belive it indicates server side issue rather then client side.

**Comment by MichalKrakow** [comment] 2019-04-11 10:59
Ok i was right, 
its so trivial. 
@alhaji-aki at poit you get 422 response everything regarding cors is on place.
Server cant access folder in your storage cause it does not exist. Just create the location you set in TusServiceProvider (->setUploadDir(storage_path('app/public/uploads')) and give user rights to save there.

All good now. 
Just to sum up:
```
// TusServiceProvider.php
public function register()
    {
        $this->app->singleton('tus-server', function ($app) {
            $server = new TusServer('redis');
            
            $server->middleware()->skip(\TusPhp\Middleware\Cors::class);

            $server
                ->setApiPath('/tus') // tus server endpoint.
                ->setUploadDir(storage_path('app/public/uploads')); // uploads dir.
            

            return $server;
        });
    }
```
Added dedicated middleware:
```
// TusCorsMiddleware.php
<?php

namespace App\Http\Middleware;

use Closure;

class TusCorsMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $headers = [
            'Access-Control-Allow-Origin' => $request->header('Origin'),
            'Access-Control-Allow-Methods' => '*',
            'Access-Control-Allow-Headers' => 'Origin, X-Requested-With, Content-Type, Content-Length, Upload-Key, Upload-Checksum, Upload-Length, Upload-Offset, Tus-Version, Tus-Resumable, Upload-Metadata',
            'Access-Control-Expose-Headers' => 'Upload-Key, Upload-Checksum, Upload-Length, Upload-Offset, Upload-Metadata, Tus-Version, Tus-Resumable, Tus-Extension, Location',
            'Access-Control-Max-Age' => 86400,
        ];

        $response = $next($request);
        
        foreach ($headers as $key => $value)
            $response->headers->set($key, $value);

        return $response;
    }
}

```
Used it with route:
```
// web.php ( also put the middleware in http/kernel )
Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*')->middleware(['tus_cors']);
```
And remeber to create location and make it writeable for scripts

cheers.

**Comment by ankitpokhrel** [comment] 2019-04-11 13:53
@MichalKrakow Thank you for posting your findings and solution 👍

**Comment by alhaji-aki** [comment] 2019-04-11 20:58
Thank you @MichalKrakow... your solution worked... Thanks to all who helped me solve this issue...

**Closed** 2019-04-11 21:04 UTC
Labels: help/support
