### ISSUE TITLE
Uploading 'hangs' when glueing

### ISSUE THREAD

**Issue by robov** [ankitpokhrel/tus-php#118] opened 2019-01-02 20:11 UTC
Your package looks awesome. I am testing it out right now.
When I upload a big file (1G) the uploading itself goes pretty quicky, but then it seems to hang here :
![image](https://user-images.githubusercontent.com/8173436/50609995-ae7ea580-0ed1-11e9-9700-f04e5d461a51.png)

I am not sure what this is... I guess this is now glueing the chunks ?
However when I close the browser during this process,, then the filesize on the server stops increasing (only 200M instead of 1G)

I am using your uppy example
Uploading smaller files works like a charm

* Any idea why it stops here at 99%
* Would a 'processing' feedback be possible
* Why does it stop glueing when the browser window is closed / or moved to a different page on the site ?

For others: To prevent request body to large I 
I had to upgrade my nginx server 
```
server {
        listen              443 ssl;
        client_max_body_size 20G;
```
and my php settings:

```
upload_max_filesize = 20G
post_max_size= 20G
```

**Comment by robov** [comment] 2019-01-02 20:11
ps. I am not using redis
Would that make a difference ?

**Comment by samundra** [comment] 2019-01-03 04:05
@robov Could you please let me know what do you mean by you are not using redis. 

If you have used the setup instruction provided on the repository itself then it already has the redis.

How did you setup the project for test?

**Comment by robov** [comment] 2019-01-03 08:09
Without redis Like this:
```
$this->app->singleton('tus-server', function ($app) {
            $server = new TusServer();
```

For the rest I followed your default instructions and used your uppy example.
I also noticed the same type of behavior on the uppy test website with the 1G file. So I guess it is something on their side.

**Comment by samundra** [comment] 2019-01-03 10:02
@ankitpokhrel Can we mark this as duplicate of https://github.com/ankitpokhrel/tus-php/issues/44 

They look to be very similar.

**Comment by ankitpokhrel** [comment] 2019-01-03 11:52
Closing as a duplicate of #44

**Closed by ankitpokhrel** 2019-01-03 11:52 UTC
Labels: duplicate
